

server:
  port: 8084

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123
    url: jdbc:mysql://192.168.2.119/springcloud?useUnicode=true&characterEncoding=utf-8
    username: root
  application:
    name: service-provider-lmh
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2


mybatis:
  config-locations: classpath:mybatis/confg.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.jk.model

