
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
elasticsearch:
  clusterName: my-application
  firstPort: 9300
  ip: 127.0.0.1
  secondPort: 9301
  thirdPort: 9302
server:
  port: 8081
spring:
  servlet:
    multipart:
      max-file-size: '10MB'
      max-request-size: 100MB
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: service-feign
  main:
    allow-bean-definition-overriding: true
  redis:
    host: localhost
    password: ''
    port: 6379
    timeout: 1000



#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
  eureka:
    enabled: true



